# casc.yaml

jenkins:
  numExecutors: 0
  nodes:
    - permanent:
        launcher:
          ssh:
            credentialsId: "jenkins-ssh-key"
            host: "${JENKINS_AGENT_041484e842cf416e930b322778e11490_IP}"
            port: 22
            sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        name: "041484e842cf416e930b322778e11490"
        remoteFS: "/var/lib/jenkins"
        retentionStrategy: "always"
    - permanent:
        labelString: "041484e842cf416e930b322778e11490 linux docker arm64"
        mode: NORMAL
        name: "041484e842cf416e930b322778e11490"
        numExecutors: 3
        remoteFS: "jenkins_home"
        launcher:
          ssh:
            credentialsId: "jenkins-controller-to-agents-private-key"
            host: "${JENKINS_AGENT_041484e842cf416e930b322778e11490_IP}"
            port: 22
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
  systemMessage: "Welcome to Jenkins!\n\n"
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  globalNodeProperties:
    - envVars:
        env:
          - key: "JENKINS_SEED_JOB_REPO_URL"
            value: "${JENKINS_SEED_JOB_REPO_URL}"
unclassified:
  location:
    url: "${JENKINS_LOCATION_URL}"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
jobs:
  - file: /usr/local/seed-job.groovy
credentials:
  system:
    domainCredentials:
      - credentials:
          - gitHubApp:
              id: "github-app-user-andrewjdawes"
              # apiUri: https://my-custom-github-enterprise.com/api/v3 # optional only required for GitHub enterprise
              appID: "${JENKINS_CREDENTIAL_GITHUB_APP_USER_ANDREWJDAWES_APP_ID}"
              description: "GitHub App for AndrewJDawes User"
              # https://stackoverflow.com/questions/67494516/with-ansible-how-do-i-write-a-private-key-to-a-text-file-without-losing-the-lef
              privateKey: "${JENKINS_CREDENTIAL_GITHUB_APP_USER_ANDREWJDAWES_SSH_KEY_PRIVATE}"
          - gitHubApp:
              id: "github-app-organization-codekaizen"
              # apiUri: https://my-custom-github-enterprise.com/api/v3 # optional only required for GitHub enterprise
              appID: "${JENKINS_CREDENTIAL_GITHUB_APP_ORGANIZATION_CODEKAIZEN_APP_ID}"
              description: "GitHub App for CodeKaizen Organization"
              # https://stackoverflow.com/questions/67494516/with-ansible-how-do-i-write-a-private-key-to-a-text-file-without-losing-the-lef
              privateKey: "${JENKINS_CREDENTIAL_GITHUB_APP_ORGANIZATION_CODEKAIZEN_SSH_KEY_PRIVATE}"
          - basicSSHUserPrivateKey:
              id: "jenkins-controller-to-agents-private-key"
              description: "Jenkins Controller to Agents Private Key"
              privateKeySource:
                directEntry:
                  privateKey: "${JENKINS_CREDENTIAL_JENKINS_CONTROLLER_TO_AGENTS_PRIVATE_KEY}"
              scope: GLOBAL
              username: "${JENKINS_AGENTS_SSH_USERNAME}"
